/// <reference path="./custom.d.ts" />
// tslint:disable
/**
 * Pokemon REST API for PPKWU5
 * Try to test some GET enpoints
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as url from "url";
import * as isomorphicFetch from "isomorphic-fetch";
import { Configuration } from "./configuration";

const BASE_PATH = "https://pokeapi.co".replace(/\/+$/, "");

/**
 *
 * @export
 */
export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

/**
 *
 * @export
 * @interface FetchAPI
 */
export interface FetchAPI {
    (url: string, init?: any): Promise<Response>;
}

/**
 *
 * @export
 * @interface FetchArgs
 */
export interface FetchArgs {
    url: string;
    options: any;
}

/**
 *
 * @export
 * @class BaseAPI
 */
export class BaseAPI {
    protected configuration: Configuration;

    constructor(configuration?: Configuration, protected basePath: string = BASE_PATH, protected fetch: FetchAPI = isomorphicFetch) {
        if (configuration) {
            this.configuration = configuration;
            this.basePath = configuration.basePath || this.basePath;
        }
    }
};

/**
 *
 * @export
 * @class RequiredError
 * @extends {Error}
 */
export class RequiredError extends Error {
    name: "RequiredError"
    constructor(public field: string, msg?: string) {
        super(msg);
    }
}

/**
 * 
 * @export
 * @interface Machine
 */
export interface Machine {
    /**
     * 
     * @type {number}
     * @memberof Machine
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof Machine
     */
    item?: number;
    /**
     * 
     * @type {number}
     * @memberof Machine
     */
    move?: number;
    /**
     * 
     * @type {string}
     * @memberof Machine
     */
    versionGroup?: string;
}
/**
 * 
 * @export
 * @interface Pokemon
 */
export interface Pokemon {
    /**
     * 
     * @type {number}
     * @memberof Pokemon
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof Pokemon
     */
    name?: number;
    /**
     * 
     * @type {number}
     * @memberof Pokemon
     */
    baseExperience?: number;
    /**
     * 
     * @type {string}
     * @memberof Pokemon
     */
    height?: string;
    /**
     * 
     * @type {string}
     * @memberof Pokemon
     */
    isDefault?: string;
    /**
     * 
     * @type {string}
     * @memberof Pokemon
     */
    order?: string;
    /**
     * 
     * @type {string}
     * @memberof Pokemon
     */
    abilities?: string;
    /**
     * 
     * @type {string}
     * @memberof Pokemon
     */
    moves?: string;
    /**
     * 
     * @type {string}
     * @memberof Pokemon
     */
    stats?: string;
    /**
     * 
     * @type {string}
     * @memberof Pokemon
     */
    types?: string;
}
/**
 * 
 * @export
 * @interface Region
 */
export interface Region {
    /**
     * 
     * @type {number}
     * @memberof Region
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof Region
     */
    locations?: number;
    /**
     * 
     * @type {number}
     * @memberof Region
     */
    move?: number;
    /**
     * 
     * @type {string}
     * @memberof Region
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Region
     */
    names?: string;
    /**
     * 
     * @type {string}
     * @memberof Region
     */
    mainGeneration?: string;
    /**
     * 
     * @type {string}
     * @memberof Region
     */
    pokedexes?: string;
    /**
     * 
     * @type {string}
     * @memberof Region
     */
    versionGroup?: string;
}
/**
 * DefaultApi - fetch parameter creator
 * @export
 */
export const DefaultApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Enter id to find Pokemon ability
         * @summary Finds Pokemon ability by Id
         * @param {number} id ID of region to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV2AbilityIdGet(id: number, options: any = {}): FetchArgs {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling apiV2AbilityIdGet.');
            }
            const localVarPath = `/api/v2/ability/{id}/`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Enter id to find Pokemon Machine
         * @summary Finds Machine by Id
         * @param {number} id ID of region to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV2MachineIdGet(id: number, options: any = {}): FetchArgs {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling apiV2MachineIdGet.');
            }
            const localVarPath = `/api/v2/machine/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Enter id to find Pokemon
         * @summary Finds pokemon by Id
         * @param {number} id ID of region to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV2PokemonIdGet(id: number, options: any = {}): FetchArgs {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling apiV2PokemonIdGet.');
            }
            const localVarPath = `/api/v2/pokemon/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Enter name to find Pokemon Info
         * @summary Finds Pokemon by Name
         * @param {string} name The name that needs to pokemon info.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV2PokemonNameGet(name: string, options: any = {}): FetchArgs {
            // verify required parameter 'name' is not null or undefined
            if (name === null || name === undefined) {
                throw new RequiredError('name','Required parameter name was null or undefined when calling apiV2PokemonNameGet.');
            }
            const localVarPath = `/api/v2/pokemon/{name}/`
                .replace(`{${"name"}}`, encodeURIComponent(String(name)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Enter id to find Pokemon region
         * @summary Finds Pokemon region by id
         * @param {number} id ID of region to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV2RegionIdGet(id: number, options: any = {}): FetchArgs {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling apiV2RegionIdGet.');
            }
            const localVarPath = `/api/v2/region/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Enter id to find Pokemon ability
         * @summary Finds Pokemon ability by Id
         * @param {number} id ID of region to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV2AbilityIdGet(id: number, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const localVarFetchArgs = DefaultApiFetchParamCreator(configuration).apiV2AbilityIdGet(id, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response;
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * Enter id to find Pokemon Machine
         * @summary Finds Machine by Id
         * @param {number} id ID of region to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV2MachineIdGet(id: number, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const localVarFetchArgs = DefaultApiFetchParamCreator(configuration).apiV2MachineIdGet(id, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response;
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * Enter id to find Pokemon
         * @summary Finds pokemon by Id
         * @param {number} id ID of region to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV2PokemonIdGet(id: number, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const localVarFetchArgs = DefaultApiFetchParamCreator(configuration).apiV2PokemonIdGet(id, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response;
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * Enter name to find Pokemon Info
         * @summary Finds Pokemon by Name
         * @param {string} name The name that needs to pokemon info.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV2PokemonNameGet(name: string, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const localVarFetchArgs = DefaultApiFetchParamCreator(configuration).apiV2PokemonNameGet(name, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response;
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * Enter id to find Pokemon region
         * @summary Finds Pokemon region by id
         * @param {number} id ID of region to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV2RegionIdGet(id: number, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const localVarFetchArgs = DefaultApiFetchParamCreator(configuration).apiV2RegionIdGet(id, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response;
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * Enter id to find Pokemon ability
         * @summary Finds Pokemon ability by Id
         * @param {number} id ID of region to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV2AbilityIdGet(id: number, options?: any) {
            return DefaultApiFp(configuration).apiV2AbilityIdGet(id, options)(fetch, basePath);
        },
        /**
         * Enter id to find Pokemon Machine
         * @summary Finds Machine by Id
         * @param {number} id ID of region to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV2MachineIdGet(id: number, options?: any) {
            return DefaultApiFp(configuration).apiV2MachineIdGet(id, options)(fetch, basePath);
        },
        /**
         * Enter id to find Pokemon
         * @summary Finds pokemon by Id
         * @param {number} id ID of region to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV2PokemonIdGet(id: number, options?: any) {
            return DefaultApiFp(configuration).apiV2PokemonIdGet(id, options)(fetch, basePath);
        },
        /**
         * Enter name to find Pokemon Info
         * @summary Finds Pokemon by Name
         * @param {string} name The name that needs to pokemon info.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV2PokemonNameGet(name: string, options?: any) {
            return DefaultApiFp(configuration).apiV2PokemonNameGet(name, options)(fetch, basePath);
        },
        /**
         * Enter id to find Pokemon region
         * @summary Finds Pokemon region by id
         * @param {number} id ID of region to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV2RegionIdGet(id: number, options?: any) {
            return DefaultApiFp(configuration).apiV2RegionIdGet(id, options)(fetch, basePath);
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * Enter id to find Pokemon ability
     * @summary Finds Pokemon ability by Id
     * @param {number} id ID of region to return
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiV2AbilityIdGet(id: number, options?: any) {
        return DefaultApiFp(this.configuration).apiV2AbilityIdGet(id, options)(this.fetch, this.basePath);
    }

    /**
     * Enter id to find Pokemon Machine
     * @summary Finds Machine by Id
     * @param {number} id ID of region to return
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiV2MachineIdGet(id: number, options?: any) {
        return DefaultApiFp(this.configuration).apiV2MachineIdGet(id, options)(this.fetch, this.basePath);
    }

    /**
     * Enter id to find Pokemon
     * @summary Finds pokemon by Id
     * @param {number} id ID of region to return
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiV2PokemonIdGet(id: number, options?: any) {
        return DefaultApiFp(this.configuration).apiV2PokemonIdGet(id, options)(this.fetch, this.basePath);
    }

    /**
     * Enter name to find Pokemon Info
     * @summary Finds Pokemon by Name
     * @param {string} name The name that needs to pokemon info.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiV2PokemonNameGet(name: string, options?: any) {
        return DefaultApiFp(this.configuration).apiV2PokemonNameGet(name, options)(this.fetch, this.basePath);
    }

    /**
     * Enter id to find Pokemon region
     * @summary Finds Pokemon region by id
     * @param {number} id ID of region to return
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiV2RegionIdGet(id: number, options?: any) {
        return DefaultApiFp(this.configuration).apiV2RegionIdGet(id, options)(this.fetch, this.basePath);
    }

}
