/**
 * Pokemon REST API for PPKWU5
 * Try to test some GET enpoints
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as api from "poke-api/api"
import { Configuration } from "poke-api/configuration"

const config: Configuration = {}

describe("DefaultApi", () => {
  let instance: api.DefaultApi
  beforeEach(function() {
    instance = new api.DefaultApi(config)
  });

  test("apiV2AbilityIdGet", () => {
    const id: number = 789
    return expect(instance.apiV2AbilityIdGet(id, {})).resolves.toBe(null)
  })
  test("apiV2MachineIdGet", () => {
    const id: number = 789
    return expect(instance.apiV2MachineIdGet(id, {})).resolves.toBe(null)
  })
  test("apiV2PokemonIdGet", () => {
    const id: number = 789
    return expect(instance.apiV2PokemonIdGet(id, {})).resolves.toBe(null)
  })
  test("apiV2PokemonNameGet", () => {
    const name: string = "name_example"
    return expect(instance.apiV2PokemonNameGet(name, {})).resolves.toBe(null)
  })
  test("apiV2RegionIdGet", () => {
    const id: number = 789
    return expect(instance.apiV2RegionIdGet(id, {})).resolves.toBe(null)
  })
})

