// tslint:disable
/**
 * Pokemon REST API for PPKWU5
 * Try to test some GET enpoints
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

export * from "poke-api/api";
export * from "poke-api/configuration";
